#! /usr/bin/env bash

export TENSOR_DIR="/var/data/tensorflow"
export TENSOR_TGZ="/home/ubuntu/app/notebook.tgz"

if [ ! -d "${TENSOR_DIR}" ] && [ -f "${TENSOR_TGZ}" ]; then
  mkdir -p "${TENSOR_DIR}"
  cd "${TENSOR_DIR}"
  cp "${TENSOR_TGZ}" "${TENSOR_DIR}"
  tar xfvz "$(basename ${TENSOR_TGZ})"
fi

tensorboard --logdir "/var/lib/lxc/data/tensorflow/tensorflow_training/logs" && killall -9 tensorboard
